title: MyProject
description: Description of my Project
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
excerpt_separator: "<!--more-->"
baseurl: "/MyProject"
url: "https://sqqaazz.github.io"